### ISSUE TITLE
Security Improved. Subresource Integrity missing.

### ISSUE THREAD

**Issue by yuansong862** [PandoraPay/PandoraPay-wallet#12]
Security Improved using Subresource Integrity. Please accept PULL https://github.com/PandoraPay/PandoraPay-wallet/pull/11

**Comment by ibudisteanu** [comment]
Approved!

**Comment by yuansong862** [comment]
Please merge https://github.com/PandoraPay/PandoraPay-wallet/pull/13

**Comment by yuansong862** [comment]
PULL https://github.com/PandoraPay/PandoraPay-wallet/pull/14
