### ISSUE TITLE
No need for two distinct web worker bundles...

### ISSUE THREAD

**Issue by yuansong862** [PandoraPay/PandoraPay-wallet#16]
After further review, we just noticed that you don't need two separate bundles for running the two web workers. This PULL https://github.com/PandoraPay/PandoraPay-wallet/pull/15 saves ~40kb and simplifies the overall architecture.

**Comment by ibudisteanu** [comment]
Basically your proposal in pull request #15  is to remove the second web worker file and to keep it identical with the first one ?

**Comment by ibudisteanu** [comment]
But for example, Pandora Storage is initialized for the 2nd web worker which doesn't need it
