### ISSUE TITLE
Security Enhancement Proposal. Cross-platform Desktop apps!

### ISSUE THREAD

**Issue by yuansong862** [PandoraPay/PandoraPay-wallet#20]
We should have the wallet as a cross-platform desktop app. This can be done using Electron JS https://www.electronjs.org/

**Comment by ibudisteanu** [comment]
I don't think this is necessary. Users could save the web page of the wallet ( Ctrl+S ). Then users could use the web wallet safely which is stored locally on their machine.

**Comment by yuansong862** [comment]
This is not enough. Users could be encouraged to download the binaries and used them locally.

**Comment by yuansong862** [comment]
One of our devs integrated Pandora Pay FRONTEND into an ELECTRON JS application. He also optimized the Helper to run using a local host server. Kindly check and fork this repository https://github.com/yuansong862/pandorapay-electron-js

**Comment by ibudisteanu** [comment]
Wow. Really cool! So, if I understood correctly, the web wallet runs identically in the electron js version right ? It simply opens the web wallet using an embedded chromium webview. 

How do I run it ? I just install it and copy the dist/build from the frontend ?

**Comment by yuansong862** [comment]
it is simple. Just copy and build/dist from the FRONTEND and paste it into  electron js dist directory. You will also need  to append the index.html and add `<script src="/electron-app.js"></script>` in the head

**Comment by ibudisteanu** [comment]
Will you do an Ionic app for Mobile too ?

**Comment by ibudisteanu** [comment]
I was just testing your changes. Next time when you send a pull request please test it before. I noticed many bugs that were introduced in the code.

**Comment by ibudisteanu** [comment]
Check this issue https://github.com/PandoraPay/pandorapay-electron-js/issues/2

**Comment by ibudisteanu** [comment]
@yuansong862 when I run ./build electron-helper I get this error cp: target '../pandorapay-electron-js/dist/helper' is not a directory

**Comment by ibudisteanu** [comment]
@yuansong862  Check this https://github.com/PandoraPay/pandorapay-electron-js/commit/660770ecb6ccdc0caf141be33c701db24fe1177e

**Comment by ibudisteanu** [comment]
I was able to test your repository in electron, but I noticed the hCaptcha used for the faucet is not working. I had to manually send coins from a full node for testing the wallet.

**Comment by yuansong862** [comment]
HCAPTCHA doesn't allow running it on electron. Best solution is to remove the HCAPTCHA from Wallet and use it iframe.

**Comment by ibudisteanu** [comment]
Any idea how to make hCaptcha think it is not an Electron app ?

**Comment by yuansong862** [comment]
Verify https://github.com/PandoraPay/PandoraPay-wallet/pull/23 https://github.com/PandoraPay/go-pandora-pay/pull/36
HCAPTCHA is now iframe. Faucet works now in the ELECTRON JS

**Comment by ibudisteanu** [comment]
I think we should close this issue.
