### ISSUE TITLE
bug report. if tx fails when broadcasting (old data), the form should go one tab behind

### ISSUE THREAD

**Issue by xiangwei22** [PandoraPay/PandoraPay-wallet#3]
some users reported a bug. if tx fails when broadcasting (due to old data already), the form should go one tab behind. this way tx becomes valid with fresh data.

**Comment by ibudisteanu** [comment]
Let me understand your bug report. In case of an transaction propagation error, the wizzard tab index should switch with one tab backward ? Wouldn't the user select to go back and create the tx again ?

**Comment by xiangwei22** [comment]
yes. some users don't know how to use the wallet.

**Comment by ibudisteanu** [comment]
I think the best way would be to do like it an infinite loop. If any change is being detected that will invalidate the transaction, the transaction would have to be reconstructed. This way we don't show any error to the end user and the entire process is automatic. One solution would be to allow the web wallet to subscribe to the entire sender ring and listen to changes.

**Comment by ibudisteanu** [comment]
I have been thinking more about the issue you posted. I think the best way would be the solution proposed by me. This way it would not show any error message. It is a little bit tricky to implement because it requires to subscribe to all sender ring members.

**Comment by ibudisteanu** [comment]
Is this commit solving your issue https://github.com/PandoraPay/PandoraPay-wallet/commit/683fdf6f12e78d8b284e0b3f0796c0a29e42a65f ?

**Comment by xiangwei22** [comment]
yes !!
