### ISSUE TITLE
feature request. explorer search bar

### ISSUE THREAD

**Issue by xiangwei22** [PandoraPay/PandoraPay-wallet#4]
feature request. every blockchain explorer i have seen has a search bar. this allows users to explore the blockchain. the search bar should work for addresses, blocks and txs.

**Comment by ibudisteanu** [comment]
It makes sense to have a search bar. I will do an implementation in a few hours.

**Comment by ibudisteanu** [comment]
see commit https://github.com/PandoraPay/PandoraPay-wallet/commit/a6d02580198ad5c9c58f0bc28d726573494f82c3

**Comment by ibudisteanu** [comment]
Check commit https://github.com/PandoraPay/PandoraPay-wallet/commit/a6d02580198ad5c9c58f0bc28d726573494f82c3 The  new version  requires a new wasm build.

**Comment by xiangwei22** [comment]
thanks
